- name: Install necessities and nice-to-haves
  apt: pkg=$item state=installed
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - git
    - screen
    - lm-sensors
    - sensord

- name: Enable TRIM support
    lineinfile: dest=/etc/lvm/lvm.conf regexp="issue_discards" Line="    issue_discards = 1"
- copy: src=etc_cron.daily_trim dest=/etc/cron.daily/trim owner=root group=root

- name: Enable Sensors
    shell: /usr/bin/yes | /usr/sbin/sensors-detect

- name: Change grub defaults
    copy: src=etc_default_grub dest=/etc/default/grub
- command: /usr/sbin/update-grub2

- include: python.yml tags=python
- include: dnsmasq.yml tags=dnsmasq
- include: ifplugd.yml tags=ifplugd
- include: network.yml tags=network
